SQR: MACRO &A , &B
     LOAD &A
     SUB IMPAR
     STORE &A
     LOAD &B
     ADD ONE
     STORE &B
     LOAD &A
     JMPZ QUADRADO + 44
     JMPN QUADRADO + 26
     LOAD IMPAR
     ADD TWO
     STORE IMPAR
     JMP QUADRADO
     LOAD &B
     SUB ONE
     STORE &B
     LOAD &A
     ADD &B
     JMPN QUADRADO + 44
     LOAD &B
     ADD ONE
     STORE &B
     LOAD ONE
     STORE IMPAR
     ENDMACRO
     
     INPUT N
QUADRADO: SQR N , TEMP
     OUTPUT TEMP
     STOP
N: SPACE
TEMP: SPACE
ONE: CONST 1
IMPAR: CONST 1
TWO: CONST 2
AAA: SPACE
